### ISSUE TITLE
(discussion point) what will negative values for speeds do to the mean?...

### ISSUE THREAD

**Issue by clairelbromley** [dougkelly88/ClaireDataAnalysis#45]
Need to think about whether I should be including data with negative speeds
Something I need to get my head around the maths for!
xx

**Comment by dougkelly88** [comment]
Since these are ~= 0 anyway, they are probably just noise and shouldn't significantly affect the conclusions reached. In the case of any significantly non-zero negative speeds, these shouldn't affect the median too much but might be worth drawing attention to in discussion. 

(Can't force positive as direction is important)

**Comment by clairelbromley** [comment]
![image](https://cloud.githubusercontent.com/assets/13903697/12644560/85059e3c-c5bb-11e5-803b-952d8d335049.png)

**Comment by clairelbromley** [comment]
Will drag down the mean- function of how negative and how many negative values have

Less impact on the median- will only drag down as a function of how many negative values have

No effect on the max
